[workspace]
members=["tcpserver","tcpclient","chapter02", "async-chat", "list1", "list2", "list3", "list4", "list5", "closure", "benchmark", "practice", "process", "minigrep", "threadpool", "actionkv"]
resolver = "2"
